sudo: false

language: python

python:
    - "2.7"
    - "3.6"

install:
    - chmod +x devtools/travis/install.sh
    - source devtools/travis/install.sh
    - pip install --user .

script:
    - cd tests && pytest --cov=aimtools .

after_success:
    - codecov

before_cache:
    - rm -rf $HOME/miniconda/conda-bld
    - rm -f $HOME/miniconda/pkgs/*.tar.bz2
    - rm -f $HOME/.cache/pip/log/debug.log

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/miniconda

notifications:
    email: True
