sudo: false

language: python

python:
    - "2.7"
    - "3.6"

install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi    
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r 
    - conda config --add channels omnia --add channels conda-forge
    - conda create -y -n myenv python=$PYTHON_VERSION numpy scipy pandas parmed pytest pytest-cov codecov
    - source activate myenv
    - python --version
    - pip install --user .

script:
    - cd aimtools/tests && pytest --cov=aimtools .

after_success:
    - codecov

#cache:
#    directories:
#        - $HOME/.cache/pip
#        - $HOME/miniconda3
#before_cache:
#     - rm -rf $HOME/miniconda3/conda-bld
#     - rm $HOME/miniconda3/pkgs/*.tar.bz2
notifications:
    email: false
