sudo: false

language: python

python:
    - "2.7"
    - "3.6"

install:
    - if [ -d "$HOME/miniconda" ]; then
        export PATH="$HOME/miniconda/bin:$PATH"
        conda list
        pip list
      else
        if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        fi
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        conda config --add channels omnia --add channels conda-forge
        conda create -y -n myenv python=$TRAVIS_PYTHON_VERSION numpy scipy pandas parmed pytest pytest-cov codecov
      fi
    - source activate myenv
    - python --version
    - pip install --user .

script:
    - cd aimtools/tests && pytest --cov=aimtools .

after_success:
    - codecov

before_cache:
    - rm -rf $HOME/miniconda/conda-bld
    - rm -f $HOME/miniconda/pkgs/*.tar.bz2
    - rm -f $HOME/.cache/pip/log/debug.log

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/miniconda

notifications:
    email: True
